### PR TITLE
87 task use case frontend

### PR DESCRIPTION
**Pull request by JJ-Han**
completed basic layout in TaskView for the use case of creating a task

### CODE REVIEW

**Review by nargesmn100 — CHANGES_REQUESTED** [review]
Typo in TaskState class: It seems like there is a typo in the method name. It should be setUseCase instead of setUseCsae.

Thank you for fixing the infinite recursion in TaskViewModel, everything else looks good!

**Comment by JJ-Han** [comment]
fixed the typo

**Review by JJ-Han — COMMENTED** [review]
fixed the typo

**Review by nargesmn100 — APPROVED** [review]
Everything looks good now, thanks!

**Pull request merged**
