### PR TITLE
changed the implementation of the 'back' button on EventView

### PR DESCRIPTION
**Pull request by JJ-Han**
EventController now includes the EventPresenter.
In cases where the given use case does not interact with entities, the controller can directly call the presenter to execute it.

EventState class has been created and is injected into the EventViewModel.

### CODE REVIEW

**Comment by nargesmn100** [comment]
Implementation looks good, thanks! Can you add JavaDoc to the files you've made changes to?

**Review by jolateral — COMMENTED** [review]
Just a quick comment about having the controller access/use the presenter - does that violate clean architecture? Since from the diagram it looks like the interactor is the one that has to call the presenter.

**Comment by JJ-Han** [comment]
> Implementation looks good, thanks! Can you add JavaDoc to the files you've made changes to?

added Javadoc


> Just a quick comment about having the controller access/use the presenter - does that violate clean architecture? Since from the diagram it looks like the interactor is the one that has to call the presenter.

I had the same concern about the controller using the presenter.  According to the prof, it could be acceptable in certain situations.

**Comment by nargesmn100** [comment]
Sounds good, JavaDoc is nice! We should ask the TA if our situation counts as "certain situations" on Monday to guarantee we're on the right path.

**Review by nargesmn100 — APPROVED** [review]
Javadoc has been added correctly. 

The controller accessing/using the presenter does not violate clean architecture
. According to the professor's feedback, the dependency could be acceptable and reasonable in certain situations. Clean Architecture allows for dependencies within a given layer, so there wouldn't be any violations with what we have implemented.

**Pull request merged**
